########################################################################################
CTOOLS_DIR=CTools/
CTOOLS_TEST_DIR=${CTOOLS_DIR}Test/
CTOOLS_c=CTools.c
CTOOLS_h=CTools.h
CTOOLS_o=CTools.o
CTOOLS_TEST_c=Test.c
CTOOLS_TEST_h=Test.h
CTOOLS_TEST_o=Test.o
CTOOLS_TEST_DRIVER_c=Driver.c
CTOOLS_TEST_DRIVER_h=Driver.h
CTOOLS_TEST_DRIVER_o=Driver.o

CTOOLS_c_PATH=${CTOOLS_DIR}${CTOOLS_c}
CTOOLS_h_PATH=${CTOOLS_DIR}${CTOOLS_h}
CTOOLS_o_PATH=${CTOOLS_DIR}${CTOOLS_o}

CTOOLS_TEST_c_PATH=${CTOOLS_TEST_DIR}${CTOOLS_TEST_c}
CTOOLS_TEST_h_PATH=${CTOOLS_TEST_DIR}${CTOOLS_TEST_h}
CTOOLS_TEST_o_PATH=${CTOOLS_TEST_DIR}${CTOOLS_TEST_o}

CTOOLS_TEST_DRIVER_c_PATH=${CTOOLS_TEST_DIR}${CTOOLS_TEST_DRIVER_c}
CTOOLS_TEST_DRIVER_h_PATH=${CTOOLS_TEST_DIR}${CTOOLS_TEST_DRIVER_h}
CTOOLS_TEST_DRIVER_o_PATH=${CTOOLS_TEST_DIR}${CTOOLS_TEST_DRIVER_o}

CTOOLS_TEST_c_PRODUCTION_DEPENDENCIES=${CTOOLS_c_PATH} ${CTOOLS_TEST_c_PATH}
CTOOLS_TEST_h_PRODUCTION_DEPENDENCIES=${CTOOLS_h_PATH} ${CTOOLS_TEST_h_PATH}
CTOOLS_TEST_o_PRODUCTION_DEPENDENCIES=${CTOOLS_o_PATH} ${CTOOLS_TEST_o_PATH}

CTOOLS_TEST_c_DEVELOPER_DEPENDENCIES=${CTOOLS_c_PATH} ${CTOOLS_TEST_c_PATH} ${CTOOLS_TEST_DRIVER_c_PATH}
CTOOLS_TEST_h_DEVELOPER_DEPENDENCIES=${CTOOLS_h_PATH} ${CTOOLS_TEST_h_PATH} ${CTOOLS_TEST_DRIVER_h_PATH}
CTOOLS_TEST_o_DEVELOPER_DEPENDENCIES=${CTOOLS_o_PATH} ${CTOOLS_TEST_o_PATH} ${CTOOLS_TEST_DRIVER_o_PATH}

CToolsDeveloper: ${CTOOLS_TEST_c_DEVELOPER_DEPENDENCIES} ${CTOOLS_TEST_h_DEVELOPER_DEPENDENCIES}
	cd ${CTOOLS_DIR}; gcc -c ${CTOOLS_c}
	cd ${CTOOLS_TEST_DIR}; gcc -c ${CTOOLS_TEST_c} ${CTOOLS_TEST_DRIVER_c}

CToolsDeveloperClean: ${CTOOLS_TEST_o_DEVELOPER_DEPENDENCIES}
	cd ${CTOOLS_DIR}; rm -f ${CTOOLS_o}
	cd ${CTOOLS_TEST_DIR}; rm -f ${CTOOLS_TEST_o} ${CTOOLS_TEST_DRIVER_o}


########################################################################################

ALL_TEST_c_DEVELOPER_DEPENDENCIES=\
${CTOOLS_TEST_c_DEVELOPER_DEPENDENCIES}


ALL_TEST_h_DEVELOPER_DEPENDENCIES=\
${CTOOLS_TEST_h_DEVELOPER_DEPENDENCIES}

ALL_TEST_o_DEVELOPER_DEPENDENCIES=\
${CTOOLS_TEST_o_DEVELOPER_DEPENDENCIES} 

ALL_TEST_c_PRODUCTION_DEPENDENCIES=\
${CTOOLS_c} ${CTOOLS_TEST_c}

ALL_TEST_h_PRODUCTION_DEPENDENCIES=\
${CTOOLS_h} ${CTOOLS_TEST_h}

ALL_TEST_o_PRODUCTION_DEPENDENCIES=\
${CTOOLS_o} ${CTOOLS_TEST_o}

ALL_TEST_c_DEVELOPER_FILES= \
${CTOOLS_c_PATH} ${CTOOLS_TEST_c_PATH} ${CTOOLS_TEST_DRIVER_c_PATH}

ALL_TEST_h_DEVELOPER_FILES= \
${CTOOLS_h_PATH} ${CTOOLS_TEST_h_PATH} ${CTOOLS_TEST_DRIVER_h_PATH}
  
ALL_TEST_o_DEVELOPER_FILES=\
${CTOOLS_o_PATH} ${CTOOLS_TEST_o_PATH}


allDeveloperTests: ${ALL_TEST_c_DEVELOPER_DEPENDENCIES} ${ALL_TEST_h_DEVELOPER_DEPENDENCIES}
	make CToolsAutomataDeveloper


allDeveloperTestsLink: ${ALL_TEST_o_DEVELOPER_DEPENDENCIES}
	(gcc -o allDevTest ${ALL_DEV_TEST_o_FILES}) 

allDeveloperTestsClean: ${ALL_TEST_o_DEVELOPER_DEPENDENCIES}
	make CToolsDeveloperClean
	
allDeveloperTestsRun: ${ALL_TEST_c_DEVELOPER_DEPENDENCIES} ${ALL_TEST_h_DEVELOPER_DEPENDENCIES}
	make allDeveloperTestsClean
	make allDeveloperTests
	make allDeveloperTestsLink
	./allDevTest
########################################################################################