test:
	(gcc -o AutomataTest Automata.c Test.c)

automata:
	(cd Automata; make all)

combinatorics:
	(cd Combinatorics; make all)

crypto:
	(cd Crypto; make all)

matrix:
	(cd Matrix; make all)

statistics:
	(cd Statistics; make all)

utils:
	(cd Utils; make all)

utilsAssertions:
	(cd Utils; cd Assertions; make all)

utilsDictionary:
	(cd Utils; cd Dictionary; make all)

utilsRand:
	(cd Utils; cd Rand; make all)

utilsReference:
	(cd Utils; cd Reference; make all)

utilsTypes:
	(cd Utils; cd Types; make all)

utilsArray:
	(cd Utils; cd Types; cd Array; make all)

utilsFloat:
	(cd Utils; cd Types; cd Float; make all)

utilsLinkList:
	(cd Utils; cd Types; cd LinkList; make all)

utilsNumber:
	(cd Utils; cd Types; cd Number; make all)

utilsString:
	(cd Utils; cd Types; cd String; make all)

utilsUnicode:
	(cd Utils; cd Types; cd Unicode; make all)



clean:
	(cd Automata; make clean)
	(cd Combinatorics; make clean)
	(cd Crypto; make clean)
	(cd Matrix; make clean)
	(cd Statistics; make clean)
	(cd Utils; make clean)
	rm ./Test.o
