testAll:
	(cd Automata; make test)
	(cd Combinatorics; make test)
	(cd Crypto; make test)
	(cd Matrix; make test)
	(cd Statistics; make test)
	(cd Utils; make test)
	(gcc -o TestAll Test.c)

testCleanAll:
	(cd Automata; make testCleanAll)
	(cd Combinatorics; make testCleanAll)
	(cd Crypto; make testCleanAll)
	(cd Matrix; make testCleanAll)
	(cd Statistics; make testCleanAll)
	(cd Utils; make testCleanAll)
	rm ./Test.o

#AUTOMATA
testAutomata:
	(cd Automata; make test)
testCleanAutomata:
	(cd Automata; make testCleanAll)


#COMBINATORICS
testCombinatorics:
	(cd Combinatorics; make test)
testCleanCombinatorics:
	(cd Combinatorics; make testCleanAll)


#CRYPTO
testCrypto:
	(cd Crypto; make test)
testCleanCrypto:
	(cd Crypto; make testCleanAll)


#MATRIX
testMatrix:
	(cd Matrix; make test)
testCleanMatrix:
	(cd Matrix; make testCleanAll)


#STATISTICS
testStatistics:
	(cd Statistics; make test)
testCleanStatistics:
	(cd Statistics; make testCleanAll)


#UTILS
testUtils:
	(cd Utils; make test)
testCleanUtils:
	(cd Utils; make testCleanAll)


#UTILS/ASSERTIONS
testUtilsAssertions:
	(cd Utils; cd Assertions; make test)
testCleanUtilsAssertions:
	(cd Utils; cd Assertions; make testCleanAll)


#UTILS/DICTIONARY
testUtilsDictionary:
	(cd Utils; cd Dictionary; make test)
testCleanUtilsDictionary:
	(cd Utils; cd Dictionary; make testCleanAll)


#UTILS/RAND
testUtilsRand:
	(cd Utils; cd Rand; make test)
testCleanUtilsRand:
	(cd Utils; cd Rand; make testCleanAll)


#UTILS/REFERENCE
testUtilsReference:
	(cd Utils; cd Reference; make test)
testCleanUtilsReference:
	(cd Utils; cd Reference; make testCleanAll)


#UTILS/TYPES
testUtilsTypes:
	(cd Utils; cd Types; make test)
testCleanUtilsTypes:
	(cd Utils; cd Types; make testCleanAll)


#UTILS/TYPES/ARRAY
testUtilsTypesArray:
	(cd Utils; cd Types; cd Array; make test)
testCleanUtilsTypesArray:
	(cd Utils; cd Types; cd Array; make testCleanAll)


#UTILS/TYPES/FLOAT
testUtilsTypesFloat:
	(cd Utils; cd Types; cd Float; make test)
testCleanUtilsTypesFloat:
	(cd Utils; cd Types; cd Float; make testCleanAll)


#UTILS/TYPES/LINKLIST
testUtilsTypesLinkList:
	(cd Utils; cd Types; cd LinkList; make test)
testCleanUtilsTypesLinkList:
	(cd Utils; cd Types; cd LinkList; make testCleanAll)


#UTILS/TYPES/NUMBER
testUtilsTypesNumber:
	(cd Utils; cd Types; cd Number; make test)
testCleanUtilsTypesNumber:
	(cd Utils; cd Types; cd Number; make testCleanAll)


#UTILS/TYPES/STRING
testUtilsTypesString:
	(cd Utils; cd Types; cd String; make test)
testCleanUtilsTypesString:
	(cd Utils; cd Types; cd String; make testCleanAll)


#UTILS/TYPES/UNICODE
testUtilsTypesUnicode:
	(cd Utils; cd Types; cd Unicode; make test)
testCleanUtilsTypesUnicode:
	(cd Utils; cd Types; cd Unicode; make testCleanAll)


