testAll:
	(cd Automata; make testAll)
	(cd Combinatorics; make testAll)
	(cd Crypto; make testAll)
	(cd Matrix; make testAll)
	(cd Statistics; make testAll)
	(cd Utils; make testAll)
	(gcc -o TestAll Test.c)

testCleanAll:
	(cd Automata; make testCleanAll)
	(cd Combinatorics; make testCleanAll)
	(cd Crypto; make testCleanAll)
	(cd Matrix; make testCleanAll)
	(cd Statistics; make testCleanAll)
	(cd Utils; make testCleanAll)
	rm ./Test.o

#AUTOMATA
testAutomata:
	(cd Automata; make testAll)
testCleanAutomata:
	(cd Automata; make testCleanAll)


#COMBINATORICS
testCombinatorics:
	(cd Combinatorics; make testAll)
testCleanCombinatorics:
	(cd Combinatorics; make testCleanAll)


#CRYPTO
testCrypto:
	(cd Crypto; make testAll)
testCleanCrypto:
	(cd Crypto; make testCleanAll)


#MATRIX
testMatrix:
	(cd Matrix; make testAll)
testCleanMatrix:
	(cd Matrix; make testCleanAll)


#STATISTICS
testStatistics:
	(cd Statistics; make testAll)
testCleanStatistics:
	(cd Statistics; make testCleanAll)


#UTILS
testUtils:
	(cd Utils; make testAll)
testCleanUtils:
	(cd Utils; make testCleanAll)


#UTILS/ASSERTIONS
testUtilsAssertions:
	(cd Utils; cd Assertions; make testAll)
testCleanUtilsAssertions:
	(cd Utils; cd Assertions; make testCleanAll)


#UTILS/DICTIONARY
testUtilsDictionary:
	(cd Utils; cd Dictionary; make testAll)
testCleanUtilsDictionary:
	(cd Utils; cd Dictionary; make testCleanAll)


#UTILS/RAND
testUtilsRand:
	(cd Utils; cd Rand; make testAll)
testCleanUtilsRand:
	(cd Utils; cd Rand; make testCleanAll)


#UTILS/REFERENCE
testUtilsReference:
	(cd Utils; cd Reference; make testAll)
testCleanUtilsReference:
	(cd Utils; cd Reference; make testCleanAll)


#UTILS/TYPES
testUtilsTypes:
	(cd Utils; cd Types; make testAll)
testCleanUtilsTypes:
	(cd Utils; cd Types; make testCleanAll)


#UTILS/TYPES/ARRAY
testUtilsTypesArray:
	(cd Utils; cd Types; cd Array; make testAll)
testCleanUtilsTypesArray:
	(cd Utils; cd Types; cd Array; make testCleanAll)


#UTILS/TYPES/FLOAT
testUtilsTypesFloat:
	(cd Utils; cd Types; cd Float; make testAll)
testCleanUtilsTypesFloat:
	(cd Utils; cd Types; cd Float; make testCleanAll)


#UTILS/TYPES/LINKLIST
testUtilsTypesLinkList:
	(cd Utils; cd Types; cd LinkList; make testAll)
testCleanUtilsTypesLinkList:
	(cd Utils; cd Types; cd LinkList; make testCleanAll)


#UTILS/TYPES/NUMBER
testUtilsTypesNumber:
	(cd Utils; cd Types; cd Number; make testAll)
testCleanUtilsTypesNumber:
	(cd Utils; cd Types; cd Number; make testCleanAll)


#UTILS/TYPES/STRING
testUtilsTypesString:
	(cd Utils; cd Types; cd String; make testAll)
testCleanUtilsTypesString:
	(cd Utils; cd Types; cd String; make testCleanAll)


#UTILS/TYPES/UNICODE
testUtilsTypesUnicode:
	(cd Utils; cd Types; cd Unicode; make testAll)
testCleanUtilsTypesUnicode:
	(cd Utils; cd Types; cd Unicode; make testCleanAll)


